### ISSUE TITLE
UniCodeDecodeError during compilation on Arch Linux

### ISSUE THREAD

**Issue by helma** [ayyi/samplecat#31] opened 2017-10-07 16:38 UTC
I am trying to build samplecat on Arch Linux (4.13.3-1-ARCH #1 SMP PREEMPT) and get the following error during `make`:
```
Making all in gdl
make[3]: Entering directory '/home/ch/Download/src/samplecat/lib/gdl'
glib-genmarshal \
        --prefix=gdl_marshal ./libgdlmarshal.list --header > xgen-gmc \
&& cp xgen-gmc libgdlmarshal.h \
&& rm -f xgen-gmc
INFO: Reading ./libgdlmarshal.list...
echo "#include \"libgdlmarshal.h\"" > xgen-gmc \
&& glib-genmarshal \
        --prefix=gdl_marshal ./libgdlmarshal.list --body >> xgen-gmc \
&& cp xgen-gmc libgdlmarshal.c \
&& rm -f xgen-gmc
INFO: Reading ./libgdlmarshal.list...
glib-mkenums \
                --fhead "#include <glib-object.h>\n" \
                --fhead "#include \"libgdltypebuiltins.h\"\n\n" \
                --fprod "\n/* enumerations from \"@filename@\" */" \
                --vhead "static const G@Type@Value _@enum_name@_values[] = {" \
                --vprod "  { @VALUENAME@, \"@VALUENAME@\", \"@valuenick@\" }," \
                --vtail "  { 0, NULL, NULL }\n};\n\n" \
                --vtail "GType\n@enum_name@_get_type (void)\n{\n" \
                --vtail "  static GType type = 0;\n\n" \
                --vtail "  if (!type)\n" \
                --vtail "    type = g_@type@_register_static (\"@EnumName@\", _@enum_name@_values);\n\n" \
                --vtail "  return type;\n}\n\n" \
        gdl.h gdl-tools.h gdl-dock.h gdl-dock-object.h gdl-dock-master.h gdl-dock-item.h gdl-dock-item-grip.h gdl-dock-layout.h gdl-dock-bar.h gdl-dock-placeholder.h debug.h > xgen-gtbec \
&& cp xgen-gtbec libgdltypebuiltins.c \
&& rm -f xgen-gtbec
Traceback (most recent call last):
  File "/usr/bin/glib-mkenums", line 688, in <module>
    process_file(fname)
  File "/usr/bin/glib-mkenums", line 420, in process_file
    line = curfile.readline()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 244: invalid continuation byte
make[3]: *** [Makefile:840: libgdltypebuiltins.c] Error 1
make[3]: Leaving directory '/home/ch/Download/src/samplecat/lib/gdl'
make[2]: *** [Makefile:413: all-recursive] Error 1
make[2]: Leaving directory '/home/ch/Download/src/samplecat/lib'
make[1]: *** [Makefile:539: all-recursive] Error 1
make[1]: Leaving directory '/home/ch/Download/src/samplecat'
make: *** [Makefile:428: all] Error 2
```
Do you have any idea which file might contain the invalid continuation byte and how to fix it?

**Comment by ayyi** [comment] 2017-10-10 21:56
This appears to be the a acute character in the copyright notice in many of the .c and .h files in the lib/gdl directory. I will commit a fix for this hopefully tomorrow.
Thanks for reporting

**Comment by ayyi** [comment] 2017-10-12 20:45
Please let me know if the change fixes the issue for you. Thanks

**Comment by helma** [comment] 2017-10-13 12:07
Thanks a lot! Compilation works without problems now, but I get a segmentation fault if I try to start the program. The GUI appears briefly, before the program fails. I am using the dwm tiling window manager without a desktop environment.
```
Samplecat. Version 0.2.5
database is sqlite.
Segmentation fault (core dumped)
```
Should I close this issue and open a new one?

**Comment by ayyi** [comment] 2017-10-13 20:55
Glad to hear that fixed the problem. For the segfault problem, if you can please follow the instructions on using different layouts described in https://github.com/ayyi/samplecat/issues/27 and perhaps we can narrow down the cause of the problem
Thanks again for reporting the issue.

**Closed by ayyi** 2017-10-13 20:55 UTC
